[profile.release]
#codegen-units = 1
debug = true
lto = true
opt-level = 3
panic = 'abort'

[workspace]
members = [
  'asset_test',

  'core',
  'collector',
  'connector',
  'evemon_to_json',
  'sde_parser',
  'server',
]
