[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
panic = 'abort'

[workspace]
members = [
  'collector',
  'db',
  'eve_api',
  'eve_sde_parser',
  'eve_sde_parser2',
  'server',
]
