[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
panic = 'abort'

[workspace]
members = [
  'collector',
  'connector',
  'db',
  'eve_data_wrapper',
  'evemon_to_json',
  'server',
  'server_v2',
]
