[package]
name = "evemon_to_json"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.134", features = ["derive"] }
serde_json = "1.0.76"
quick-xml = { version = "0.22.0", features = ["serialize"] }
