[package]
name = "eve_server"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
async-std = { version = "1.6.5", features = ["attributes", "tokio02"] }
eve_online_api = { path = "../eve_api" }
eve_sde_parser = { path = "../eve_sde_parser" }
futures = "0.3.6"
log = "0.4.11"
morgan = { path = "../morgan" }
rusoto_cloudwatch = "0.45.0"
serde = { version = "1.0.116", features = ["derive"] }
surf = "2.0.0"
tide = "0.13.0"