[package]
name = "caph_server"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1.51"
axum = { version = "0.2.8", features = ["headers"] }
caph_connector = { path = "../connector" }
chrono = "0.4.19"
dotenv = "0.15.0"
headers = "0.3.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sqlx = { version = "0.5.9", features = ["chrono", "runtime-tokio-rustls", "postgres", "uuid", "offline"] }
tokio = { version = "1.12.0", features = ["full"] }
tracing = "0.1.29"
tracing-subscriber = "0.2.25"
uuid = { version = "0.8.2", features = ["v4", "serde"] }
