[package]
name = "caph_server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
axum = { version = "0.4.4", features = ["headers"] }
caph_connector = { path = "../connector" }
caph_core = { path = "../core" }
chrono = "0.4.19"
dotenv = "0.15.0"
headers = "0.3.5"
reqwest = "0.11.9"
serde = { version = "1.0.134", features = ["derive"] }
serde_json = "1.0.76"
sqlx = { version = "0.5.10", features = ["chrono", "runtime-tokio-rustls",
"postgres", "uuid", "offline", "json"] }
tokio = { version = "1.15.0", features = ["full"] }
tracing = "0.1.29"
tracing-subscriber =  { version = "0.3.6", features = ["env-filter"] }
uuid = { version = "0.8.2", features = ["v4", "serde"] }
