[package]
name = "caph_server"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
async-std = { version = "1.8.0", features = ["attributes", "tokio02"] }
caph_eve_online_api = { path = "../eve_api" }
futures = "0.3.8"
log = "0.4.11"
morgan = { path = "../morgan" }
serde = { version = "1.0.118", features = ["derive"] }
sqlx = { version = "0.4.1", default-features = false, features = ["macros", "runtime-async-std-rustls", "postgres"] }
tide = "0.15.0"