[package]
name = "caph_server"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
caph_eve_online_api = { path = "../eve_api" }
log = "0.4.11"
morgan = { path = "../morgan" }
serde = { version = "1.0.118", features = ["derive"] }
sqlx = { version = "0.4.1", default-features = false, features = ["macros", "runtime-tokio-rustls", "postgres"] }
tokio = { version = "0.2.24", features = ["full"] }
warp = "0.2.5"