[package]
name = "sde_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
tracing = "0.1.34"
tracing-subscriber =  { version = "0.3.11", features = ["env-filter"] }
uuid = { version = "1.0.0", features = ["v4"] }
