[package]
name = "caph_eve_sde_parser"
version = "0.1.0"
authors = ["Lars Holznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
miniz_oxide = "0.4.3"
serde = { version = "1.0.117", features = ["derive"] }
serde_yaml = "0.8.14"
surf = "2.1.0"