[package]
name = "caph_connector"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.51"
jsonwebtoken = "7.2.0"
reqwest = { version = "0.11.4", features = ["json"] }
serde = { version = "1.0.130", features = ["derive"] }
tracing = "0.1.26"
url = "2.2.2"
zip = "0.5.11"
