[package]
name = "caph_connector"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
base64 = "0.13.0"
reqwest = { version = "0.11.9", features = ["json", "rustls-tls"] }
serde = { version = "1.0.134", features = ["derive"] }
serde_json = "1.0.76"
serde_yaml = "0.8.23"
tracing = "0.1.29"
url = "2.2.2"
zip = "0.5.13"

sqlx = { version = "0.5.10", optional = true}

[features]
default = []
sqlx_types = ["sqlx"]
