[package]
name = "caph_connector"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
base64 = "0.13.0"
reqwest = { version = "0.11.7", features = ["json", "rustls-tls"] }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
serde_yaml = "0.8.23"
tracing = "0.1.29"
url = "2.2.2"
zip = "0.5.13"
