[package]
name = "caph_collector"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
async-std = { version = "1.8.0", features = ["attributes", "tokio02"] }
caph_eve_online_api = { path = "../eve_api" }
caph_eve_sde_parser = { path = "../eve_sde_parser" }
futures = "0.3.8"
log = "0.4.11"
metrics-exporter-http-async_std = "0.1.0"
metrics-runtime = "0.13.1"
morgan = { path = "../morgan" }
sqlx = { version = "0.4.1", default-features = false, features = ["macros", "runtime-async-std-rustls", "postgres"] }
