[package]
name = "caph_collector"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
caph_eve_online_api = { path = "../eve_api" }
caph_eve_sde_parser = { path = "../eve_sde_parser" }
futures = "0.3.8"
log = "0.4.11"
morgan = { git = "https://github.com/lholznagel/morgan.git", rev = "624526038c210b142d2835fa77965064771ac192" }
metrix = { git = "https://github.com/lholznagel/metrix.git", rev = "33d20d7206f18e8822ebcb272d9eed6f5d056e23" }
sqlx = { version = "0.4.1", default-features = false, features = ["macros", "runtime-tokio-rustls", "postgres"] }
tokio = { version = "0.2.24", features = ["macros", "rt-threaded", "time", "stream"] }
