[package]
name = "caph_collector"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
caph_eve_data_wrapper = { path = "../eve_data_wrapper" }
chrono = "0.4.19"
dotenv = "0.15.0"
sqlx = { version = "0.5.7", features = ["chrono", "runtime-tokio-rustls", "postgres", "uuid", "offline"] }
tokio = { version = "1.2.0", features = ["full"] }
tracing = "0.1.27"
tracing-subscriber = "0.2.22"
uuid = { version = "0.8.2", features = ["v4"]}
