[package]
name = "caph_eve_online_api"
version = "0.1.0"
authors = ["lholznagel"]
edition = "2018"

[dependencies]
log = "0.4.11"
serde = { version = "1.0.117", default-features = false, features = ["derive"] }
serde_json = "1.0.59"
surf = "2.1.0"
