[package]
name = "eve_online_api"
version = "0.1.0"
authors = ["lholznagel"]
edition = "2018"

[dependencies]
log = "0.4.11"
serde = { version = "1.0.116", default-features = false, features = ["derive"] }
surf = "2.0.0"
